// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: gRPC/chittychat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Messages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *Messages) Reset() {
	*x = Messages{}
	mi := &file_gRPC_chittychat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_chittychat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_gRPC_chittychat_proto_rawDescGZIP(), []int{0}
}

func (x *Messages) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type LamportTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lamporttimestamp int32 `protobuf:"varint,1,opt,name=lamporttimestamp,proto3" json:"lamporttimestamp,omitempty"`
}

func (x *LamportTimestamp) Reset() {
	*x = LamportTimestamp{}
	mi := &file_gRPC_chittychat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamportTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamportTimestamp) ProtoMessage() {}

func (x *LamportTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_chittychat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamportTimestamp.ProtoReflect.Descriptor instead.
func (*LamportTimestamp) Descriptor() ([]byte, []int) {
	return file_gRPC_chittychat_proto_rawDescGZIP(), []int{1}
}

func (x *LamportTimestamp) GetLamporttimestamp() int32 {
	if x != nil {
		return x.Lamporttimestamp
	}
	return 0
}

type ClientId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientid int32 `protobuf:"varint,1,opt,name=clientid,proto3" json:"clientid,omitempty"`
}

func (x *ClientId) Reset() {
	*x = ClientId{}
	mi := &file_gRPC_chittychat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientId) ProtoMessage() {}

func (x *ClientId) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_chittychat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientId.ProtoReflect.Descriptor instead.
func (*ClientId) Descriptor() ([]byte, []int) {
	return file_gRPC_chittychat_proto_rawDescGZIP(), []int{2}
}

func (x *ClientId) GetClientid() int32 {
	if x != nil {
		return x.Clientid
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_gRPC_chittychat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_chittychat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_gRPC_chittychat_proto_rawDescGZIP(), []int{3}
}

type MessagePackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message          *Messages         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Lamporttimestamp *LamportTimestamp `protobuf:"bytes,2,opt,name=lamporttimestamp,proto3" json:"lamporttimestamp,omitempty"`
}

func (x *MessagePackage) Reset() {
	*x = MessagePackage{}
	mi := &file_gRPC_chittychat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePackage) ProtoMessage() {}

func (x *MessagePackage) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_chittychat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePackage.ProtoReflect.Descriptor instead.
func (*MessagePackage) Descriptor() ([]byte, []int) {
	return file_gRPC_chittychat_proto_rawDescGZIP(), []int{4}
}

func (x *MessagePackage) GetMessage() *Messages {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessagePackage) GetLamporttimestamp() *LamportTimestamp {
	if x != nil {
		return x.Lamporttimestamp
	}
	return nil
}

type ClientPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId         *ClientId         `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	LamportTimestamp *LamportTimestamp `protobuf:"bytes,2,opt,name=lamportTimestamp,proto3" json:"lamportTimestamp,omitempty"`
}

func (x *ClientPackage) Reset() {
	*x = ClientPackage{}
	mi := &file_gRPC_chittychat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPackage) ProtoMessage() {}

func (x *ClientPackage) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_chittychat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPackage.ProtoReflect.Descriptor instead.
func (*ClientPackage) Descriptor() ([]byte, []int) {
	return file_gRPC_chittychat_proto_rawDescGZIP(), []int{5}
}

func (x *ClientPackage) GetClientId() *ClientId {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *ClientPackage) GetLamportTimestamp() *LamportTimestamp {
	if x != nil {
		return x.LamportTimestamp
	}
	return nil
}

var File_gRPC_chittychat_proto protoreflect.FileDescriptor

var file_gRPC_chittychat_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x63, 0x68, 0x69, 0x74, 0x74, 0x79, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x3e, 0x0a, 0x10, 0x4c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x6c,
	0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x26, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x74, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x12, 0x23, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x10, 0x6c, 0x61, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x75, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3d,
	0x0a, 0x10, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x61, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x6c, 0x61, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0xc1, 0x01,
	0x0a, 0x0a, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x12, 0x32, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x28, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x09, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x0a, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x17, 0x5a, 0x15, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x2f,
	0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_gRPC_chittychat_proto_rawDescOnce sync.Once
	file_gRPC_chittychat_proto_rawDescData = file_gRPC_chittychat_proto_rawDesc
)

func file_gRPC_chittychat_proto_rawDescGZIP() []byte {
	file_gRPC_chittychat_proto_rawDescOnce.Do(func() {
		file_gRPC_chittychat_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_chittychat_proto_rawDescData)
	})
	return file_gRPC_chittychat_proto_rawDescData
}

var file_gRPC_chittychat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gRPC_chittychat_proto_goTypes = []any{
	(*Messages)(nil),         // 0: Messages
	(*LamportTimestamp)(nil), // 1: LamportTimestamp
	(*ClientId)(nil),         // 2: ClientId
	(*Empty)(nil),            // 3: Empty
	(*MessagePackage)(nil),   // 4: MessagePackage
	(*ClientPackage)(nil),    // 5: ClientPackage
}
var file_gRPC_chittychat_proto_depIdxs = []int32{
	0, // 0: MessagePackage.message:type_name -> Messages
	1, // 1: MessagePackage.lamporttimestamp:type_name -> LamportTimestamp
	2, // 2: ClientPackage.clientId:type_name -> ClientId
	1, // 3: ClientPackage.lamportTimestamp:type_name -> LamportTimestamp
	5, // 4: ChittyChat.GetMessages:input_type -> ClientPackage
	4, // 5: ChittyChat.PostMessage:input_type -> MessagePackage
	3, // 6: ChittyChat.CreateClientIdentifier:input_type -> Empty
	5, // 7: ChittyChat.Disconnect:input_type -> ClientPackage
	4, // 8: ChittyChat.GetMessages:output_type -> MessagePackage
	3, // 9: ChittyChat.PostMessage:output_type -> Empty
	2, // 10: ChittyChat.CreateClientIdentifier:output_type -> ClientId
	3, // 11: ChittyChat.Disconnect:output_type -> Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gRPC_chittychat_proto_init() }
func file_gRPC_chittychat_proto_init() {
	if File_gRPC_chittychat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_chittychat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_chittychat_proto_goTypes,
		DependencyIndexes: file_gRPC_chittychat_proto_depIdxs,
		MessageInfos:      file_gRPC_chittychat_proto_msgTypes,
	}.Build()
	File_gRPC_chittychat_proto = out.File
	file_gRPC_chittychat_proto_rawDesc = nil
	file_gRPC_chittychat_proto_goTypes = nil
	file_gRPC_chittychat_proto_depIdxs = nil
}
